### PR TITLE
Update default option in `Translate` type.

### PR DESCRIPTION
**Pull request by SimplyComplexable**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
A translation can optionally `returnObjects`, which can be typed by giving a type to the `Translate` generic, but the value of the `default` options argument does not match this pattern. This adds `T` as a possible type to `default`.

**Which issue (if any) does this pull request address?**
N/A

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Review by aralroca — APPROVED** [review]

**Comment by aralroca** [comment]
Thanks for your contribution @SimplyComplexable . I changed to canary instead of master branch.

**Comment by aralroca** [comment]
@SimplyComplexable can you fix the failing test? Thanks

**Comment by SimplyComplexable** [comment]
@aralroca I got a little carried away, so let me know if you want me to simplify this, but I noticed that if you pass in an object for the `default` option the string values won't be interpolated. This addresses that, as well as making the interpolation work with arrays for both found and default values.

**Comment by SimplyComplexable** [comment]
Hi @aralroca, just following up on this. Anything else needed for this? Do you want me to pull back on the functionality changes?

**Comment by SimplyComplexable** [comment]
Hi @aralroca just following up on this again. Any concern with the changes I've made? I can deal with merge conflicts.

**Comment by SimplyComplexable** [comment]
@aralroca Any update here?

**Comment by aralroca** [comment]
@SimplyComplexable thank you for your contribution! Looks good to me! Thanks!

**Comment by aralroca** [comment]
@all-contributors please add @SimplyComplexable for code

**Pull request merged**
