### PR TITLE
feat: add support for arrays and pluralization to Trans component

### PR DESCRIPTION
**Pull request by acidfernando**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[x] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Improved Trans component usability to allow dealing with array values and pluralization just as the hook does

**Is there anything you'd like reviewers to focus on?**

I'm not convinced by the new parameter `returnObjects` I added to Trans component. Its the same as `useTranslation`.

Please treat this as a first draft. We can discuss better ways of doing this. If it is a desired feature, I'm glad to keep working on it until we are all satisfied with the outcome.

### CODE REVIEW

**Review by aralroca — APPROVED** [review]
Thanks @acidfernando LGTM! thanks for you contribution

> Please treat this as a first draft. We can discuss better ways of doing this. 

I think using the `formatElements` as you did is the correct way!

**Comment by acidfernando** [comment]
Thanks for your feedback!

I'll let you merge when you think its appropriate

**Comment by aralroca** [comment]
@all-contributors please add @acidfernando for code

**Comment by aralroca** [comment]
@acidfernando available in [2.7.0-canary.1](https://github.com/aralroca/next-translate/releases/tag/2.7.0-canary.1)

**Pull request merged**
