### PR TITLE
fix: ignore empty lang value #1162

### PR DESCRIPTION
**Pull request by timotew**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x ] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Ignore empty translations for generated pages.

**Which issue (if any) does this pull request address?**

https://github.com/aralroca/next-translate/issues/1162

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Review by esupper — APPROVED** [review]

**Review by aralroca — APPROVED** [review]
Thanks @timotew

**Comment by aralroca** [comment]
@esupper thanks, I'm going to do this change in another PR

**Comment by timotew** [comment]
Thanks @aralroca and @esupper . Unfortunately, I have not had the time to reproduce the issues that @nightire mentioned and that's why I have not added it to this change.

**Comment by aralroca** [comment]
No worry. Thank you @timotew so much for the contribution!! @all-contributors please add @timotew for code

**Pull request merged**
