### PR TITLE
Query data doesn't update when I use `returnObjects`

### PR DESCRIPTION
**Pull request by alziqziq**
**What is the purpose of this pull request? (put an "X" next to item)**

immutable effect, objects that have been interpolated change original data

[ ] Documentation update
[x] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
clone data before returning value, i use lodash.clonedeep to handle deep object, `JSON.parse(JSON.stringify())` or `Object.assign` is not good for deep object

**Which issue (if any) does this pull request address?**
issue https://github.com/aralroca/next-translate/issues/952

### CODE REVIEW

**Comment by alziqziq** [comment]
hi @aralroca thanks for your libray, i got some problem when i use `returnObject`, please review my pull request, Thank you in advance

**Comment by bagusfl95** [comment]
I need this fix for my project too.

**Review by aralroca — COMMENTED** [review]
Please add the failing test with `returnObjects` and then the solution of this failing test. Probably is possible to solve this without adding an extra dependency

**Comment by alziqziq** [comment]
unit tests added, pls review @aralroca 

### with clone object
with clonedeep


### without clone object 
without clonedeep

**Comment by Dragate** [comment]
This is quite a bump in bundle size across the board (even for situations that don't use `returnObjects`). [lodash.clonedeep](https://bundlephobia.com/package/lodash.clonedeep@4.5.0) seems to be approximately twice the size of [next-translate](https://bundlephobia.com/package/next-translate@1.6.0). There are definitely solutions (better dependency selection or even better, writing own code) that achieve the same effect with a fraction of the cost.

**Comment by alziqziq** [comment]
oke, let's use `JSON.parse(JSON.stringify())` for now, i think it works for this case.

image

**Comment by alziqziq** [comment]
hi @aralroca how about this issue? i need this changes

**Comment by StLyn4** [comment]
I'll just leave this here. JS has had a built-in feature for deep cloning for about a year. Browser support is also very good. But this approach is not suitable for older browsers.

https://developer.mozilla.org/en-US/docs/Web/API/structuredClone

https://caniuse.com/?search=structuredClone

**Review by aralroca — APPROVED** [review]

**Comment by aralroca** [comment]
it's a pitty that structuredClone is not available in all modern browsers... 😅

**Comment by aralroca** [comment]
@alziqziq please remove the `yarn.lock` & `package-lock.json` changes, after this I'm going to merge it for the next release

**Comment by aralroca** [comment]
and @alziqziq thank you for your contribution. Please @all-contributors add @alziqziq for code

**Comment by alziqziq** [comment]
> @alziqziq please remove the `yarn.lock` & `package-lock.json` changes, after this I'm going to merge it for the next release

done, please rereview @aralroca

**Review by aralroca — APPROVED** [review]

**Pull request merged**
