### PR TITLE
fix: stabilize t in app directory

### PR DESCRIPTION
**Pull request by jessemartin**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
stabilized t in app directory

**Which issue (if any) does this pull request address?**
https://github.com/aralroca/next-translate/issues/1205

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by jessemartin** [comment]
@aralroca mind taking a look?

**Review by aralroca — CHANGES_REQUESTED** [review]
This PR remember me this other PR: https://github.com/aralroca/next-translate/pull/574 that was reverted here because introduce this issue https://github.com/aralroca/next-translate/issues/604 

can you verify that now shared layouts work with your change?

**Comment by jessemartin** [comment]
This PR does not change the behavior of the hook in the Pages router, so no regression is present there. I tested out shared layouts in the App router via the `with-app-directory` and it seems to be working as intended!

https://github.com/aralroca/next-translate/assets/1626240/166c835f-98e7-40d3-9d17-d7a86cbac296

**Comment by jessemartin** [comment]
@aralroca could you please have another look at this?

**Review by aralroca — APPROVED** [review]
Thanks for the contribution

**Comment by aralroca** [comment]
@jessemartin I have updated the canary branch because in master there were changes that were not in the canary, and just failed the test "`t` is stable", could you check what happened? Thanks and sorry for the inconvenience

**Comment by jessemartin** [comment]
@aralroca looks like the problem was a merge conflict (the upstream logic had moved to `createTranslation.tsx`). I force-pushed a rebase and fix to this branch.

**Comment by aralroca** [comment]
Thanks a lot @jessemartin 😊

**Comment by aralroca** [comment]
@all-contributors please add @jessemartin for code

**Comment by kristian240** [comment]
@aralroca can you create a new canary release that ships this?

**Comment by aralroca** [comment]
@kristian240 I've pre-released [3.0.0-canary.4](https://github.com/aralroca/next-translate/releases/tag/3.0.0-canary.4) now with the latest changes in the canary branch. Give feedback if everything is ok. I have to make revision and re-take the routing for 3.0.0.

I feel that in the last months there has been a lot of focus on [Brisa framework](https://brisa.build/), now it's time to work for 3.0.0.0 version of next-translate and give good support on Next.js 15.

**Comment by kristian240** [comment]
This was quick, thanks a lot.

**Pull request merged**
