### PR TITLE
Fix error when running `next start` without sources

### PR DESCRIPTION
**Pull request by StLyn4**
**What is the purpose of this pull request? (put an "X" next to item)**

[  ] Documentation update
[X] Bug fix
[  ] New feature
[  ] Other, please explain:

**What changes did you make? (Give an overview)**
The names of the commits as well as the associated issues speak for themselves. The main change is that if we could not find the folder with the pages, then we do not use the loader (we still attach the config). The essence of the problem was that although the loaders are not used by `next start`, the code above is still executed, since the configuration itself is generated each time anew.

**Which issue (if any) does this pull request address?**
#892, #853

### CODE REVIEW

**Comment by StLyn4** [comment]
The second issue is solved by itself, since the built-in possible paths are taken out in an array and then iterated. If the value at index N is suitable, then N + 1 will not be checked

**Comment by aralroca** [comment]
@StLyn4  I have moved all the code from the branch you made from the TypeScript compiler to the canary branch. I think we can move from experimental to canary 😊

Now there are some conflicts. Feel free to fix them and we'll move this PR directly to the canary branch. 

Thank you very much!

**Comment by StLyn4** [comment]
@aralroca Done👌
By the way, can you please add me as a contributor? 😄

**Review by aralroca — APPROVED** [review]

**Comment by aralroca** [comment]
@StLyn4 of course!!! Thank you so much for all your work!

@all-contributors please add @StLyn4 for code

**Comment by aralroca** [comment]
by the way @StLyn4 , I have this error running `yarn example`:

Screenshot 2023-01-11 at 13 06 37

have you encountered the same error before? If not, I'll investigate to see what it could be... I have tried with node 16 and node 18, but with both I get this error. Thanks

**Comment by StLyn4** [comment]
@aralroca Ran `yarn example` with `node 14.20`, `node 16.19` and `node 18.13`. `Windows 11`. Everything works. It is worth noting that Next.JS reports an error about `_middleware.ts`, because in version `12.2.0` there were breaking changes regarding middlewares. Also, loading translations does not work ("Critical dependency: the request of a dependency is an expression", blah blah blah)
изображение

**Comment by aralroca** [comment]
@StLyn4 I'm trying to run properly all the examples but I have some troubles, can you help me to detect what is happening? Thank you! For example, about this example https://codesandbox.io/s/empty-morning-wqs233?file=/package.json do you now about this `Internal Server Error`? Thanks

**Comment by aralroca** [comment]
Wow! Ok! Thank you @StLyn4 !

**Pull request merged**
