### PR TITLE
[Webpack loader]: Code processing completely rewritten using Typescript Compiler API

### PR DESCRIPTION
**Pull request by StLyn4**
**What is the purpose of this pull request? (put an "X" next to item)**

[  ] Documentation update
[X] Bug fix
[  ] New feature
[X] Other, please explain:

**What changes did you make? (Give an overview)**
Well, I hope no one will be deterred by the size of the pull request.
The main goal is to rewrite the code of the loader, which is responsible for the analysis / modification of the source code of the pages. Transfer the responsibility for working directly with the code to the typescript library (we will then only have to work with abstractions).

I will answer any questions regarding the request, as well as make any corrections, if necessary. Have a nice day! 😃

**Which issue (if any) does this pull request address?**
#486, #753, #526. Also maybe #488, #827 and #774.

### CODE REVIEW

**Review by aralroca — COMMENTED** [review]
thank you for your great contribution @StLyn4. I have the doubt if we should put TypeScript as peer dependency? Or would it be equally compatible for people who don't use TypeScript?

**Comment by StLyn4** [comment]
Just tested on a project that doesn't use TypeScript. Yes, there is a problem with dependencies. I suggest adding typescript to "dependencies" rather than "peerDependencies", as the end user may not need it in such a situation. As practice shows, the loader is able to work with JS files, as long as they use es syntax (for import / export), and not commonjs. I don't think this will be a problem in the Next.js environment. Within an hour I will make a commit with corrections.

**Comment by StLyn4** [comment]
Done. Also did a rebase, for a better commit history

**Comment by aralroca** [comment]
In this case, it's a breaking change, I think the ideal will be for version 2.0. The PR looks good. We can prerelease and ask for feedback from people before releasing the 2.0 release. What do you think? Thanks for your contribution.

**Comment by StLyn4** [comment]
Totally agree with you. If it turns out that there are some bugs that appear on this particular version of the loader, then please notify me - I will do my best to fix it

**Comment by aralroca** [comment]
@StLyn4 I prerelased to [2.0.0-experimental.2](https://github.com/aralroca/next-translate/releases/tag/2.0.0-experimental.2)

I also I updated this discussion: https://github.com/aralroca/next-translate/discussions/881 

I'll to ask to the people on these issues that you commented:

> https://github.com/aralroca/next-translate/issues/486, https://github.com/aralroca/next-translate/issues/753, https://github.com/aralroca/next-translate/issues/526. Also maybe https://github.com/aralroca/next-translate/issues/488, https://github.com/aralroca/next-translate/issues/827 and https://github.com/aralroca/next-translate/issues/774.

Thank you a lot! 👍

**Pull request merged**
