### PR TITLE
Allow missing translation in Trans component with components

### PR DESCRIPTION
**Pull request by aovens-quantifi**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Added a null check in the `Trans` component so if a translation is missing and the Trans component is using components, the component will not throw

**Which issue (if any) does this pull request address?**

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Review by aralroca — APPROVED** [review]
Thanks for the contribution

**Comment by aralroca** [comment]
@all-contributors please add @aovens-quantifi for code

**Comment by aovens-quantifi** [comment]
@aralroca Can you cut a release with this in it?

**Comment by aralroca** [comment]
@aovens-quantifi done! you have [2.0.6](https://github.com/aralroca/next-translate/releases/tag/2.0.6) available. Thanks for your contribution!!!

**Pull request merged**
