### PR TITLE
Fixed the zero suffix for the plural form

### PR DESCRIPTION
**Pull request by nagman**
**What is the purpose of this pull request? (put an "X" next to item)**

[ x ] Documentation update
[ ] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
The `_zero` suffix doesn't work. But the `_0` does.

**Which issue (if any) does this pull request address?**
The plural form when count = 0

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Review by aralroca — COMMENTED** [review]
Both are supported and correct. `zero` is part of the standard plurals and is different behavior in each language:

```js
new Intl.PluralRules("ar-EG").select(0);
// → 'zero'
new Intl.PluralRules("ar-EG").select(1);
// → 'one'
new Intl.PluralRules("ar-EG").select(2);
// → 'two'
new Intl.PluralRules("ar-EG").select(6);
// → 'few'
new Intl.PluralRules("ar-EG").select(18);
// → 'many'
```

Docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules

Then we support numbers also, but works for each number, example with `999`:

```json
{
  "cart_number_999": "Cart is full"
}
```

**Comment by aralroca** [comment]
In English we only have 2 plurals: singular and plural. But there are languages with more than 2 plurals.

**Comment by nagman** [comment]
Mmmh, I see. Thanks for the explanation!

**Comment by aralroca** [comment]
Thanks for your contribution, maybe we need to explain better how plurals rule work in the Readme

**Pull request closed without merging**
