### PR TITLE
Add type safety for getT function

### LINKED ISSUE #1185: Type safety for getT function
**What version of this package are you using?**
2.6.2

**What problem do you want to solve?**
Type safety for getT function

**What do you think is the correct solution to this problem?**
update the existing docs for type safety

**Are you willing to submit a pull request to implement this change?**
yes

### PR DESCRIPTION
**Pull request by hichemfantar**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[ X ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

- refactor the `TranslateFunction` into its own interface
- add support for `getT`

**Which issue (if any) does this pull request address?**
closes #1185

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Review by aralroca — APPROVED** [review]
Thanks a lot @hichemfantar !!

**Comment by aralroca** [comment]
@all-contributors ads @hichemfantar for code

**Comment by aralroca** [comment]
* @all-contributors adds @hichemfantar for code

**Comment by aralroca** [comment]
@all-contributors add please @hichemfantar for code

**Comment by hichemfantar** [comment]
@allc add @hichemfantar 

> @all-contributors add please @hichemfantar for code

Hey, it looks like the bot added me incorrectly

**Pull request merged**
